import { Platform, Share, Clipboard } from 'react-native';

/**
 * Builds the formatted text summary for sharing.
 */
export function buildShareText({ rightAnswers, wrongAnswers, negativeMarking, totalScore, attempted, percentage }) {
    const scoreStr = Number.isInteger(totalScore)
        ? String(totalScore)
        : Number(totalScore).toFixed(2);

    const lines = [
        '📊 Exam Mark Result',
        '─────────────────────',
        `✓  Right Answers:     ${rightAnswers}`,
        `✗  Wrong Answers:     ${wrongAnswers}`,
        `🔢 Negative Marking:  ${negativeMarking}`,
        `📝 Attempted:         ${attempted}`,
        `🏆 Total Score:       ${scoreStr}`,
    ];

    if (percentage !== null) {
        lines.push(`📈 Percentage:        ${percentage.toFixed(2)}%`);
    }

    lines.push('─────────────────────');
    lines.push('Generated by ExamMark Calculator');

    return lines.join('\n');
}

/**
 * Shares or copies the result text.
 * • Web: tries navigator.share → falls back to clipboard
 * • Android: uses React Native Share sheet
 */
export async function shareResult(text) {
    if (Platform.OS === 'web') {
        if (typeof navigator !== 'undefined' && navigator.share) {
            try {
                await navigator.share({ title: 'Exam Mark Result', text });
                return { success: true, method: 'share' };
            } catch { /* user cancelled */ }
        }
        // Fallback: clipboard
        try {
            await navigator.clipboard.writeText(text);
            return { success: true, method: 'clipboard' };
        } catch { /* permissions */ }
        return { success: false };
    }

    // Native
    try {
        await Share.share({ message: text, title: 'Exam Mark Result' });
        return { success: true, method: 'share' };
    } catch {
        return { success: false };
    }
}
